name: stuartmurray
favicon: null
layout_spectrum: 0.67079
typography_spectrum: 0.13861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9e8'
    - '#431709'
    - '#6b7d51'
    - '#e8c3c0'
    - '#37a1ea'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
