name: stuartmurray
favicon: null
layout_spectrum: 0.6999012453015894
typography_spectrum: 0.10110580478794873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5ceaa'
    - '#0f0e0c'
    - '#e49959'
    - '#9e6031'
    - '#6b3b19'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
